import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {useRouter} from 'next/router'

export default function index() {
  const [email,setEmail] = useState()
  const [password,setPassword] = useState()
  const router = useRouter()

  const handleSubmit = (e) => {
    e.preventDefault();
    router.push('/profil');


  }
  return (
    <div className="">
      <Head>
        <title>JobHunt.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainContainer}>
      <div className={styles.left}>
        <Image src="/jobHuntid.png" width={50} height={20} alt="login" quality={100}/> 
        <Image src="/icon.png" width={20} height={20} alt="login" quality={100}/> 
      </div>
      <div className={styles.fromContainer}>
        <form onSubmit={handleSubmit} className={styles.forminput}>
          <p>Halo !</p>
          <p>Silahkan masukkan data di bawah ini</p>
          <input type="email" onChange={e=> setEmail(e.target.value)} placeholder="email"></input>
          <input type="password" onChange={e=> setPassword(e.target.value)} placeholder="password"></input>
          <button type='submit' onClick={e => handleSubmit(e)}>Masuk</button>
          <p>Belum punya akun? <Link href="/register">Daftar Sekarang</Link></p>
        </form>
      </div>
      </main>
    </div>
  )
}
